### ISSUE TITLE
Now using your lybrary, can't send message to private user without exception

### ISSUE THREAD

**Issue by veralfre** [leandrotoledo/python-telegram-bot#103]
import telegram
bot=telegram.Bot(token)

update_id=1
while 1:

    #DEBUG AGAIN:print(_updateId)
    updates=bot.getUpdates(update_id)
    #DEBUG:
    #for update in updates:
    #    print(update)
    if len(updates)>0:
        #Preparo i miei vari Array e dopo di che parto con le funzioni
        update=updates[0]
        message=update.message
        _chatId = update.message.chat_id
        update_id=update.update_id+1
        #Funzione di echo
        if(message.text!=None):

            #Log delle operazioni:
            """
             Message
            """
            print('Il messaggio è '+message.text+' ricevuto da ',_chatId)
            bot.sendMessage(chat_id=_chatId,text=message.text)
            if(message.text.startswith('/echo ')):
              i=0
              while(i<5):
                #result=bot.sendMessage(chat_id=_chatId,text=message.text[6:])
                #print(result)
                i+=1

            if(message.text.startswith('/bombo')):
               """
                    Preloading BomboImg
               """

               #_photoBinary=open('./bombo.jpg','rb')
               #file_info=telegram.InputFileInfo('./bombo.jpg', _photoBinary, 'image/jpg')
               #bot.sendPhoto(_chatId,file_info)

I get:
Il messaggio è Echo ricevuto da  127514757
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\utils\request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.1\helpers\pydev\pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.1\helpers\pydev\pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "C:/Users/Freddy/PycharmProjects/test/main.py", line 30, in <module>
    bot.sendMessage(chat_id=_chatId,text=message.text)
  File "C:\Python34\lib\site-packages\telegram\bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Python34\lib\site-packages\telegram\bot.py", line 158, in decorator
    result = request.post(url, data)
  File "C:\Python34\lib\site-packages\telegram\utils\request.py", line 109, in post
    raise TelegramError('Unauthorized')
telegram.error.TelegramError: Unauthorized

Process finished with exit code 1

What's the problem now? Thanks for help ;)

**Comment by leandrotoledo** [comment]
Hi @veralfre, thanks for you bug report.
Have you added your Bot to a group then you removed it? Seems like you tried to process a message in backlog pulling that doesn't have permission to contact the user/group, like I said, could be either because it was removed from a group or blocked by the user.

**Comment by veralfre** [comment]
Ok sorry for coming here so late, but the problem was I was trying to send a message to myself but I had accidentally block the bot. So the moral here is: always handle all the Exception :)
