### ISSUE TITLE
lots of urllib and ssl exceptions

### ISSUE THREAD

**Issue by mjnaderi** [leandrotoledo/python-telegram-bot#108]
When I run the code, some times I get some exceptions (different exceptions at different times), and some times it works correctly. I am using version `2.9.2`.

Some of exceptions:

```
Traceback (most recent call last):
  File "------.py", line 66, in <module>
    main()
  File "------.py", line 14, in main
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id  # Get lastest update
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/bot.py", line 689, in getUpdates
    result = request.post(url, data, network_delay=network_delay)
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 816, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 271, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'api.telegram.org' doesn't match either of 'urlp.asm.skype.com', 'urlp-asm-skype.trafficmanager.net', 'ea1-urlp.cloudapp.net', 'eus1-urlp.asm.skype.com', 'eus1-urlp.cloudapp.net', 'neu1-urlp.asm.skype.com', 'neu1-urlp.cloudapp.net', 'nus1-urlp.asm.skype.com', 'nus1-urlp.cloudapp.net', 'sa1-urlp.asm.skype.com', 'sa1-urlp.cloudapp.net', 'sus1-urlp.asm.skype.com', 'sus1-urlp.cloudapp.net', 'weu1-urlp.asm.skype.com', 'weu1-urlp.cloudapp.net', 'wus1-urlp.asm.skype.com', 'wus1-urlp.cloudapp.net'
```

I opened https://openshift.redhat.com in my browser. Then after running python code, last line of previous exception changed to:

```
ssl.CertificateError: hostname 'api.telegram.org' doesn't match either of 'openshift.com', 'enterprise.openshift.com', 'www.openshift.com', 'repo.fusesource.com', 'assets.openshift.net', 'download.jboss.org', 'www.jboss.org', 'static.jboss.org', 'downloads.jboss.org', 'developer.redhat.com', 'developers.redhat.com', 'it-developers.redhat.com', 'openshift.redhat.com'
```

Then I moved to another computer, in a different country, and following exceptions raised randomly (sometimes it worked, but one of these exception raised after some minutes):

```
Traceback (most recent call last):
  File "-------.py", line 66, in <module>
    main()
  File "-------.py", line 16, in main
    for update in bot.getUpdates(offset=LAST_UPDATE_ID):
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/bot.py", line 689, in getUpdates
    result = request.post(url, data, network_delay=network_delay)
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -5] No address associated with hostname>
```

```
Traceback (most recent call last):
  File "------.py", line 66, in <module>
    main()
  File "------.py", line 16, in main
    for update in bot.getUpdates(offset=LAST_UPDATE_ID):
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/bot.py", line 689, in getUpdates
    result = request.post(url, data, network_delay=network_delay)
  File "/home/aaa/mybot/venv/local/lib/python2.7/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```

Another exception which raised after code was running successfully for a while:

```
Traceback (most recent call last):
  File "------.py", line 66, in <module>
    main()
  File "------.py", line 16, in main
    for update in bot.getUpdates(offset=LAST_UPDATE_ID):
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/bot.py", line 689, in getUpdates
    result = request.post(url, data, network_delay=network_delay)
  File "/home/aaa/mybot/venv/lib/python2.7/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
```

**Comment by jh0ker** [comment]
I'm not sure this is related to us... Could you try running the following script for a while?

```
#!/usr/bin/env python
# Tests connection to Telegram Bot API

from urllib2 import urlopen
from time import sleep

while True:
    urlopen("https://api.telegram.org/")
    print('OK')
    sleep(1)
    urlopen("https://bot.telegram.org/")
    print('OK')
    sleep(1)
```

**Comment by mjnaderi** [comment]
On second machine, it fails after some requests. But in first machine, it always prints OK. But `getUpdates()` raises other exceptions in first machine (which I mentioned: ssl CertificateError and "EOF occurred in violation of protocol")

**Comment by leandrotoledo** [comment]
Hi @mjnaderi, have you found the root case of the problem? Seems like it's beyond the appliance layer.

**Comment by mjnaderi** [comment]
@leandrotoledo I gave up using `getUpdates`, and enabled telegram's webhooks. I get telegram's incoming updates with django and post my requests to telegram using "requests" library. It has worked good till now.
Yes I think the problem was specific to my situation. So I close this issue.
Thanks.
