### ISSUE TITLE
TelegramError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by tukhfatov** [leandrotoledo/python-telegram-bot#120]
Sometimes alarm such error:
TelegramError: urlopen error [Errno -2] Name or service not known

Traceback (most recent call last):
 File "/***/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/***", line 41, in ***
   bot.sendMessage(chat_id = '-####', text = text)
 File "/***/site-packages/telegram/bot.py", line 95, in decorator
   result = func(self, *args, **kwargs)
 File "/***/site-packages/telegram/bot.py", line 121, in decorator
   json_data = self._requestUrl(url, 'POST', data=data)
 File "/***/site-packages/telegram/bot.py", line 692, in _requestUrl
   raise TelegramError(str(e))
TelegramError: urlopen error [Errno -2] Name or service not known

Run on Apache, Django Framework.

Please suggest and advise how to solve.

**Comment by jh0ker** [comment]
It seems like that is caused by your internet connection being lost.

**Comment by jh0ker** [comment]
Hey, if your error still persists, feel free to reopen the issue!

**Comment by tukhfatov** [comment]
Please check the error message below 
![713235274_972_7336077732516321034](https://cloud.githubusercontent.com/assets/2496303/11894631/563cb068-a59a-11e5-9c4b-128eb053acf6.jpg)

**Comment by BrnoPCmaniak** [comment]
@jh0ker It seems to me as still an Issue because I came across this.

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f111399d630>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/filip/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/poolmanager.py", line 165, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot<BOT_TOKEN>/sendMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f111399d630>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    schedule.run_pending()
  File "/home/filip/.local/lib/python3.5/site-packages/schedule/__init__.py", line 367, in run_pending
    default_scheduler.run_pending()
  File "/home/filip/.local/lib/python3.5/site-packages/schedule/__init__.py", line 64, in run_pending
    self._run_job(job)
  File "/home/filip/.local/lib/python3.5/site-packages/schedule/__init__.py", line 96, in _run_job
    ret = job.run()
  File "/home/filip/.local/lib/python3.5/site-packages/schedule/__init__.py", line 293, in run
    ret = self.job_func()
  File "main.py", line 14, in base
    ":kissing_heart:", use_aliases=True))
  File "/home/filip/.local/lib/python3.5/site-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/home/filip/.local/lib/python3.5/site-packages/telegram/bot.py", line 150, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/filip/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/home/filip/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 138, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot<BOT_TOKEN>/sendMessage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f111399d630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

```
$ pip3 freeze
blivet==1.20.3
borgbackup==1.0.7
certifi==2016.9.26
chardet==2.2.1
coverage==4.2
decorator==4.0.10
dnf-langpacks==0.15.1
emoji==0.3.9
fail2ban==0.9.5
future==0.16.0
iniparse==0.4
initial-setup==0.3.40
langtable==0.0.35
llfuse==1.1.1
msgpack-python==0.4.8
ntplib==0.3.3
ordered-set==2.0.0
pid==2.0.1
pwquality==1.3.0
pygobject==3.20.1
pygpgme==0.3
PyIscsi==1.0
pykickstart==2.25
pyparted==3.10.7
PySocks==1.5.6
python-meh==0.43
python-telegram-bot==5.2.0
pytz==2016.6.1
pyudev==0.21.0
requests==2.10.0
requests-file==1.4
requests-ftp==0.3.1
rpm-python==4.13.0rc1
schedule==0.3.2
six==1.10.0
slip==0.6.4
slip.dbus==0.6.4
SSSDConfig==1.14.2
systemd-python==232
urllib3==1.15.1
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```python
import schedule
import emoji
import time
import telegram

TOKEN = ""  # Some Bot Token
CHAT_ID = 0  # Some CHAT_ID

bot = telegram.Bot(token=TOKEN)

def base():
    bot.sendMessage(chat_id=CHAT_ID, text=emoji.emojize("Message1", use_aliases=True))

def check():
    bot.sendMessage(chat_id=CHAT_ID, text=emoji.emojize("Message2", use_aliases=True))

schedule.every().day.at("22:00").do(base)
schedule.every().day.at("22:10").do(check)

while True:
    schedule.run_pending()
    time.sleep(schedule.idle_seconds())
```

This also happened on the first from the first run of bot.sendMessage from console, but after second run it worked fine. And Now on this long running script it does the same.
