### ISSUE TITLE
TypeError: <_io.BufferedWriter name='webhook_cert.pem'> is not JSON serializable

### ISSUE THREAD

**Issue by CapitainCrunch** [leandrotoledo/python-telegram-bot#124]
I'm trying to run bot w/ webhook.

In order to create a cert, I used
openssl req -new -x509 -days 3650 -key webhook_pkey.pem -out webhook_cert.pem

What am I doing wrong?

Traceback (most recent call last):
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 167, in <module>
    main()
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 138, in main
    certificate=open('webhook_cert.pem', 'wb'))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 725, in setWebhook
    result = request.post(url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 101, in post
    data = json.dumps(data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <_io.BufferedWriter name='webhook_cert.pem'> is not JSON serializable

**Comment by jh0ker** [comment]
@CapitainCrunch You're using open(..., 'wb') which is opening the file for write access. You should use 'rb' instead

**Comment by CapitainCrunch** [comment]
so, is it bug? I've just copy-pasted it with no changes

**Comment by jh0ker** [comment]
Indeed, it was a bug in the example code. Thank you! I just fixed it. Feel free to reopen the issue if you have any more problems :)

**Comment by CapitainCrunch** [comment]
I guess, something wrong with my cert. What could it be? First time to it :(

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 167, in <module>
    main()
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 138, in main
    certificate=open('webhook_cert.pem', 'rb'))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 725, in setWebhook
    result = request.post(url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 118, in post
    raise TelegramError(message)
telegram.error.TelegramError: [Error]: Bad webhook: [Error]: Failed to set custom cert file

**Comment by CapitainCrunch** [comment]
Something wrong with cert? 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 106, in post
    result = urlopen(request, timeout=timeout).read()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 167, in <module>
    main()
  File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 138, in main
    certificate=open('webhook_cert.pem', 'rb'))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 725, in setWebhook
    result = request.post(url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 118, in post
    raise TelegramError(message)
telegram.error.TelegramError: [Error]: Bad webhook: [Error]: Failed to set custom cert file
