### ISSUE TITLE
telegram.error.TelegramError: [Error]: Bad webhook: [Error]: Failed to set custom cert file

### ISSUE THREAD

**Issue by CapitainCrunch** [leandrotoledo/python-telegram-bot#125]
Something wrong with cert?
To create it I used 
openssl req -new -x509 -days 3650 -key webhook_pkey.pem -out webhook_cert.pem

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 106, in post
result = urlopen(request, timeout=timeout).read()
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
return opener.open(url, data, timeout)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
response = meth(req, response)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
'http', request, response, code, msg, hdrs)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
return self._call_chain(args)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
result = func(args)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 167, in 
main()
File "/Users/Bogdan/Desktop/Projects/Bitbucket/hseshedule_bot/webhook_test.py", line 138, in main
certificate=open('webhook_cert.pem', 'rb'))
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
result = func(self, args, *kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/bot.py", line 725, in setWebhook
result = request.post(url, data)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telegram/utils/request.py", line 118, in post
raise TelegramError(message)
telegram.error.TelegramError: [Error]: Bad webhook: [Error]: Failed to set custom cert file

**Comment by jh0ker** [comment]
Try: `openssl req -new -x509 -nodes -newkey rsa:1024 -keyout webhook_pkey.key -out webhook_cert.pem -days 3650`

**Comment by CapitainCrunch** [comment]
yeah, that works
I got 
2015-12-09 15:58:45,885 - telegram.dispatcher - INFO - Dispatcher thread started
2015-12-09 15:58:45,885 - telegram.updater - INFO - Updater thread started
2015-12-09 15:58:45,886 - telegram.utils.webhookhandler - INFO - Webhook Server started.

**Comment by CapitainCrunch** [comment]
BUT

  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/updater.py", line 192, in _start_webhook
    self.update_queue, url_path)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/webhookhandler.py", line 21, in __init__
    RequestHandlerClass)
  File "/usr/lib/python3.4/socketserver.py", line 430, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 444, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

**Comment by jh0ker** [comment]
Seems like you don't have permissions to bind to the port. Check if the port is used by something else or try running as root.

**Comment by CapitainCrunch** [comment]
Maybe, it's router?

**Comment by jh0ker** [comment]
This error should not be related to a router, but if your machine is in a NATed network, setting up a webhook is a bit more complicated.

**Comment by jh0ker** [comment]
Hey, is the error still present or can I close the issue?

**Comment by CapitainCrunch** [comment]
I haven't solved the problem yet, but I'm sure it's due to permission. Thanks for help!

**Comment by jh0ker** [comment]
No problem :+1:
