### ISSUE TITLE
Photos can't be printed

### ISSUE THREAD

**Issue by FichteFoll** [leandrotoledo/python-telegram-bot#13]
Trying to stringify a message that contains a photo results in the following exception:

```
Traceback (most recent call last):
  File "E:\Development\Python\codetalkircbot\codegram.py", line 82, in <module>
    main()
  File "E:\Development\Python\codetalkircbot\codegram.py", line 78, in main
    bot.poll_loop(SLEEP)
  File "E:\Development\Python\codetalkircbot\codegram.py", line 67, in poll_loop
    self.handle_updates(updates)
  File "E:\Development\Python\codetalkircbot\codegram.py", line 43, in handle_updates
    print(update)
  File "E:\Development\Python\codetalkircbot\venv\lib\site-packages\telegram\update.py", line 32, in __str__
    return self.to_json()
  File "E:\Development\Python\codetalkircbot\venv\lib\site-packages\telegram\update.py", line 28, in to_json
    json_data['message'] = self.message.to_json()
  File "E:\Development\Python\codetalkircbot\venv\lib\site-packages\telegram\message.py", line 184, in to_json
    json_data['photo'] = self.photo.to_json()
AttributeError: 'list' object has no attribute 'to_json'
```

`Message.photo` is a list of `PhotoSize` objects. Should be easy to handle along with #12.

**Comment by leandrotoledo** [comment]
Thank you for your bug report, I'll be looking into this.

**Comment by leandrotoledo** [comment]
Commit f4ad7037e16b60dffa06e20759b0b5050d554316 has fixed this issue, thanks for reporting it in.
