### ISSUE TITLE
can't pickle lock objects

### ISSUE THREAD

**Issue by leandrotoledo** [leandrotoledo/python-telegram-bot#31]
As stated by @JokerQyou the recent version doesn't allow to pickle objects::
`>>> pickle.dump(bot, open('save.p', 'wb'))`

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/pickle.py", line 1370, in dump
        Pickler(file, protocol).dump(obj)
      File "/usr/lib/python2.7/pickle.py", line 224, in dump
        self.save(obj)
      File "/usr/lib/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
      File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
        save(state)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
      File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
        save(state)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 600, in save_list
        self._batch_appends(iter(obj))
      File "/usr/lib/python2.7/pickle.py", line 615, in _batch_appends
        save(x)
      File "/usr/lib/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
      File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
        save(state)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 331, in save
        self.save_reduce(obj=obj, *rv)
      File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
        save(state)
      File "/usr/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/usr/lib/python2.7/pickle.py", line 663, in _batch_setitems
        save(v)
      File "/usr/lib/python2.7/pickle.py", line 306, in save
        rv = reduce(self.proto)
      File "/home/leandrotoledo/workspace/python-telegram-bot/env/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
        raise TypeError, "can't pickle %s objects" % base.__name__
    TypeError: can't pickle lock objects

Mostly because nested classes, but it needs further investigation.

**Comment by leandrotoledo** [comment]
All pickle needs to know to reconstruct Bot object is the token and base_url (if any), this has been defined in Bot.__reduce__. Please give it a try and let us know if it works.

**Comment by leandrotoledo** [comment]
Released on v2.5.2

**Comment by leandrotoledo** [comment]
Unpickle wasn't working due a base_url + token concatenation, fixed ``__reduce__`` func on 3974690b907c0678326798e4472cef8420270ea9

**Comment by leandrotoledo** [comment]
Released on v2.5.3
