### ISSUE TITLE
Unable to JSON serialize forwarded messages

### ISSUE THREAD

**Issue by JokerQyou** [leandrotoledo/python-telegram-bot#38]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 558, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/joker/projects/bot/operations.py", line 50, in handle_update
    handle_command(text, message)
  File "/home/joker/projects/bot/operations.py", line 77, in handle_command
    result = getattr(botcommands, command)(message, debug=debug)
  File "/home/joker/projects/bot/config.py", line 85, in wrapper
    MQTT['topic'], payload=msg.to_json(),
  File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 40, in to_json
    return json.dumps(self.to_dict())
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <telegram.user.User object at 0xf44c50> is not JSON serializable
```

**Comment by leandrotoledo** [comment]
https://github.com/leandrotoledo/python-telegram-bot/blob/master/telegram/message.py#L210

It should be foward_from.to_dict() instead.

**Comment by leandrotoledo** [comment]
This issue has been fixed, one more note though, `` message.to_json() `` will take care of serialization for you, it also works for any other telegram class object.
