### ISSUE TITLE
Logging exception

### ISSUE THREAD

**Issue by Shevraar** [leandrotoledo/python-telegram-bot#78]
Basically I'm receiving messages in italian, and we have various characters that are not included in the ascii table such as: é, ó, à, í,  ú, etc.
Bear in mind that I am not using a filehandler to write the log but since I'm on uwsgi I'm using a StreamHandler and I cannot pass the encoding to the StreamHandler

This is the log:

> ```2015-10-10 10:04:28,708|DEBUG   |14345|telegram.bot|bot|Entering: sendMessage
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 966, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 548: ordinal not in range(128)
Call stack:
  File "/home/shevraar/dev/venv/jovabot/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shevraar/dev/venv/jovabot/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shevraar/dev/venv/jovabot/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shevraar/dev/venv/jovabot/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./jovabot/__init__.py", line 115, in telegram_hook
    jova_do_something(update.message)
  File "./jovabot/__init__.py", line 76, in jova_do_something
    parse_mode=parse_mode)
  File "/home/shevraar/dev/venv/jovabot/lib/python3.4/site-packages/telegram/bot.py", line 127, in decorator
    logger.debug(result)
Message: <telegram.message.Message object at 0x7fde9bfcafd0>
Arguments: ()
2015-10-10 10:04:29,173|DEBUG   |14345|telegram.bot|bot|Exiting: sendMessage```

Thank you

**Comment by leandrotoledo** [comment]
@Shevraar would you paste a piece of code so I can try to reproduce?

**Comment by Shevraar** [comment]
@leandrotoledo Don't worry it wasn't your problem, I found out you can change the sys.stdout encoding by doing this (in python3): 

```python
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

logging.basicConfig(handlers=[logging.StreamHandler(sys.stdout)], level=logging.DEBUG, format='%(asctime)-15s|%(levelname)-8s|%(process)d|%(name)s|%(module)s|%(message)s')
```
