### ISSUE TITLE
Pyton does not define a variable .bot

### ISSUE THREAD

**Issue by DrSverlyat** [leandrotoledo/python-telegram-bot#83]
I have a problem at the beginning of the path )
the derivation of information about token bot, an error :
>>> import telegram
>>> bot = telegram.Bot(token= 'token')
>>> print bot.getMe()
SyntaxError: invalid syntax
>>>

**Comment by phikui** [comment]
are you using python 3?

If yes, then you have to use 
`print(bot.getMe())`

**Comment by DrSverlyat** [comment]
Yes, I am using v3. I tried what you suggested , here is the result :
>>> import telegram
>>> bot = telegram.Bot(token= 'token')
>>> print(bot.getMe())
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    print(bot.getMe())
  File "C:\Program Files\Python\lib\site-packages\telegram\bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\telegram\bot.py", line 176, in getMe
    result = request.get(url)
  File "C:\Program Files\Python\lib\site-packages\telegram\utils\request.py", line 66, in get
    return _parse(result)
  File "C:\Program Files\Python\lib\site-packages\telegram\utils\request.py", line 47, in _parse
    data = json.loads(json_data.decode())
  File "C:\Program Files\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by leandrotoledo** [comment]
@DrSverlyat just to make sure, you have replaced the 'token' on Bot(token='token') by the token given by  BotFather, right?

**Comment by DrSverlyat** [comment]
Thank you ! I'm a fool ...
